version: '3.4'

services:
  risk.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  risk.sampleclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  djclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

 # justin_client:
 #   environment:
 #     - ASPNETCORE_ENVIRONMENT=Development
 #   ports:
 #     - "80"
 #   volumes:
 #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

#  kaydonsclient:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+:443;http://+:80
#    ports:
#      - "80"
#      - "443"
#    volumes:
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  stuartclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

 # tannerclient:
 #   environment:
 #     - ASPNETCORE_ENVIRONMENT=Development
 #     - ASPNETCORE_URLS=http://+:80
 #   ports:
 #     - "80"
 #   volumes:
 #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  wyattclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  brennanclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  emmanuel_client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  hmclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


#
  rusty_client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
   

  maksad_client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

